# Home Dashboard 后端配置

server:
  port: "8090"
  mode: debug # debug 或 release

# Basic 认证配置
auth:
  enabled: false
  username: "admin"
  password: "admin"

# 页面配置文件存放目录
pages_dir: "./pages"

# 前端构建目录
frontend_dir: "./frontend/build"

# 默认导航配置
navs:
  - name: "Home"
    icon: "fas fa-home"
    url: "/"
  - name: "Tools"
    icon: "fas fa-tools"
    url: "/tools"
  - name: "Another"
    icon: "fas fa-star"
    url: "/another"

